#! /usr/bin/env python
import time

img_version=time.strftime("%Y-%m-%d")
edition="lxqt" # home, security 
device="cpi4" # rpi more will be added soon
arch="aarch64" # aarch64, armv7h
img_name="RebornOS-ARM-cpi4-" + img_version
install_dir="arch"
fs="btrfs" # ext4 or btrfs
img_type="image" # image (img.xz) or rootfs (tar.gz)
img_backend="loop" # loop or qemu-nbd
# append root=PARTUUID=XXXXXX-02 + CMDLINE will always be added to the kernel command line
# if you use btrfs you need add rootflags=subvol=@
cmdline=" loglevel=3 rootwait rw init=/sbin/init rootfstype=btrfs rootflags=subvol=@ cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory swapaccount=1 irqchip.gicv3_pseudo_nmi=0 switolb=1 coherent_pool=2M  console=ttyS0,115200n81"
configtxt='''
label RebornOS ARM
    kernel /vmlinuz-linux-cpi
    initrd /initramfs-linux-cpi.img
    devicetreedir /dtbs/
    fdt /dtbs/rockchip/rk3588s-cp4.dtb
'''
